# Generated by Django 3.1.4 on 2021-01-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210118_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='a.jpg', upload_to='images/'),
        ),
    ]
