# Generated by Django 3.1.4 on 2021-01-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210118_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='b.jpg', upload_to='images/'),
        ),
    ]
